config/routes.rb
Rails.application.routes.draw do
  root "chatrooms#index"

  resources :chatrooms
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  include CableReady::Broadcaster
  include ApplicationHelper

  after_save do
    cable_ready["message-stream"].morph(
      selector: "#chatroom-#{self.chatroom_id}",
      html: MessagesController.render(partial: "message", locals: { message: Chatroom.find(self.chatroom_id).messages, chatroom: self.chatroom_id })
    )
    cable_ready.broadcast
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = @chatroom.messages
  end

  def create
    @chatroom = Chatroom.find(params[:id].to_i)
    @message = @chatroom.messages.create(message_params).save
  end

  private
    def message_params
      params.require(:message).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paint(string)
    pp Paint["~~~~~~~~~~~~~~~~~#{string}~~~~~~~~~~~~~~~~~", :magenta, :bright]
  end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chatrooms/index.html.erb
<% @chatrooms.each do |c| %>
  <%= link_to "Join chatroom #{c.id}", message_path(c.id) %>
  <br>
<% end %>

app/views/chatrooms/show.html.erb
<p>This is the chatroom with id <%= @chatroom.id %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealTimeChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="chatroom-<%= chatroom %>">
  <% message.each do |m| %>
    <p><%= m.created_at %>: <%= m.text %></p>
  <% end %>
</div>

app/views/messages/index.html.erb
<h1 id="title">Chatroom</h1>

<%= form_with model: Message.new do |form| %>
  <%= form.text_field :text %>
  <%= form.submit "Submit" %>
<% end %>

<p> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ </p>

<%= render partial: "message" %>

app/views/messages/show.html.erb
<h1 id="title">Chatroom</h1>

<%= form_with model: Message.new, url: "/messages", method: :post do |form| %>
  <%= form.text_field :text %>
  <%= hidden_field_tag :id, value = @chatroom.id %>
  <%= form.submit "Submit" %>
<% end %>

<p> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ </p>

<%= render partial: "message", locals: { message: @message, chatroom: @chatroom.id } %>